modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL3 / CC BY-NC-ND 4.0"

[[mods]]
modId = "tacz"
version = "1.1.8"
displayName = "Timeless and Classics Zero"
authors = "Serene Wave Studio | Timeless Squad"
description = ''''''
logoFile = "icon.png"
itemIcon = "tacz:gun_smith_table"

[[mixins]]
config = "tacz.mixins.json"

[[dependencies."tacz"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacz"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacz"]]
modId = "shouldersurfing"
mandatory = false
versionRange = "[1.21.1-4.0.0,)"
ordering = "NONE"
side = "CLIENT"